// Code generated by go-envied. DO NOT EDIT.
// Generated merged configuration file for all environments

package config

import "github.com/petrovyuri/go-envied"

// ConfigInterface defines the interface for all generated configurations
type ConfigInterface interface {
	GetDATABASE_URL() string
	GetDEBUG_MODE() bool
	GetPORT() int
	GetTEMPERATURE() float64
	GetMAX_TOKENS() string
}

// Static key for TEMPERATURE in dev environment
var DEV__enviedkeyTEMPERATURE = []int{1449781530, 4028288318, 417819965}

// Static encrypted data for TEMPERATURE in dev environment
var DEV__envieddataTEMPERATURE = []int{1449781546, 4028288272, 417819916}

// Static key for MAX_TOKENS in dev environment
var DEV__enviedkeyMAX_TOKENS = []int{1449781530, 4028288318, 417819965, 358674232}

// Static encrypted data for MAX_TOKENS in dev environment
var DEV__envieddataMAX_TOKENS = []int{1449781560, 4028288271, 417819917, 358674202}

// Static key for DATABASE_URL in dev environment
var DEV__enviedkeyDATABASE_URL = []int{1449781530, 4028288318, 417819965, 358674232, 1112285527, 3123658374, 3694091696, 2501759624, 468961263, 292956477, 2265301925, 334514377, 121595214, 4089868386, 2296291581, 3756391431}

// Static encrypted data for DATABASE_URL in dev environment
var DEV__envieddataDATABASE_URL = []int{1449781630, 4028288347, 417819979, 358674197, 1112285491, 3123658471, 3694091716, 2501759721, 468961165, 292956508, 2265301974, 334514348, 121595235, 4089868311, 2296291471, 3756391531}

// DevConfigConfig - generated configuration for dev environment
type DevConfigConfig struct {
	PORT int
	TEMPERATURE float64
	MAX_TOKENS string
	DATABASE_URL string
	DEBUG_MODE bool
}

// NewDevConfigConfig creates a new configuration for dev environment
func NewDevConfigConfig() *DevConfigConfig {
	return &DevConfigConfig{
		PORT: envied.ParseInt("10000"),
		TEMPERATURE: envied.ParseFloat(envied.DeobfuscateString(DEV__enviedkeyTEMPERATURE, DEV__envieddataTEMPERATURE)),
		MAX_TOKENS: envied.DeobfuscateString(DEV__enviedkeyMAX_TOKENS, DEV__envieddataMAX_TOKENS),
		DATABASE_URL: envied.DeobfuscateString(DEV__enviedkeyDATABASE_URL, DEV__envieddataDATABASE_URL),
		DEBUG_MODE: envied.ParseBool("true"),
	}
}

// Getter methods for DevConfigConfig
func (c *DevConfigConfig) GetPORT() int {
	return c.PORT
}

func (c *DevConfigConfig) GetTEMPERATURE() float64 {
	return c.TEMPERATURE
}

func (c *DevConfigConfig) GetMAX_TOKENS() string {
	return c.MAX_TOKENS
}

func (c *DevConfigConfig) GetDATABASE_URL() string {
	return c.DATABASE_URL
}

func (c *DevConfigConfig) GetDEBUG_MODE() bool {
	return c.DEBUG_MODE
}

// Static key for DATABASE_URL in prod environment
var PROD__enviedkeyDATABASE_URL = []int{1449781530, 4028288318, 417819965, 358674232, 1112285527, 3123658374, 3694091696, 2501759624, 468961263, 292956477, 2265301925, 334514377, 121595214, 4089868386, 2296291581, 3756391431, 3804484360}

// Static encrypted data for DATABASE_URL in prod environment
var PROD__envieddataDATABASE_URL = []int{1449781610, 4028288332, 417819986, 358674268, 1112285562, 3123658466, 3694091729, 2501759740, 468961166, 292956511, 2265301956, 334514362, 121595179, 4089868367, 2296291464, 3756391541, 3804484452}

// Static key for TEMPERATURE in prod environment
var PROD__enviedkeyTEMPERATURE = []int{1449781530, 4028288318, 417819965}

// Static encrypted data for TEMPERATURE in prod environment
var PROD__envieddataTEMPERATURE = []int{1449781546, 4028288272, 417819909}

// Static key for MAX_TOKENS in prod environment
var PROD__enviedkeyMAX_TOKENS = []int{1449781530, 4028288318, 417819965, 358674232, 1112285527, 3123658374}

// Static encrypted data for MAX_TOKENS in prod environment
var PROD__envieddataMAX_TOKENS = []int{1449781560, 4028288271, 417819917, 358674184, 1112285543, 3123658404}

// ProdConfigConfig - generated configuration for prod environment
type ProdConfigConfig struct {
	DEBUG_MODE bool
	PORT int
	TEMPERATURE float64
	MAX_TOKENS string
	DATABASE_URL string
}

// NewProdConfigConfig creates a new configuration for prod environment
func NewProdConfigConfig() *ProdConfigConfig {
	return &ProdConfigConfig{
		DEBUG_MODE: envied.ParseBool("false"),
		PORT: envied.ParseInt("80"),
		TEMPERATURE: envied.ParseFloat(envied.DeobfuscateString(PROD__enviedkeyTEMPERATURE, PROD__envieddataTEMPERATURE)),
		MAX_TOKENS: envied.DeobfuscateString(PROD__enviedkeyMAX_TOKENS, PROD__envieddataMAX_TOKENS),
		DATABASE_URL: envied.DeobfuscateString(PROD__enviedkeyDATABASE_URL, PROD__envieddataDATABASE_URL),
	}
}

// Getter methods for ProdConfigConfig
func (c *ProdConfigConfig) GetDEBUG_MODE() bool {
	return c.DEBUG_MODE
}

func (c *ProdConfigConfig) GetPORT() int {
	return c.PORT
}

func (c *ProdConfigConfig) GetTEMPERATURE() float64 {
	return c.TEMPERATURE
}

func (c *ProdConfigConfig) GetMAX_TOKENS() string {
	return c.MAX_TOKENS
}

func (c *ProdConfigConfig) GetDATABASE_URL() string {
	return c.DATABASE_URL
}

